### ISSUE TITLE
Strip HTML from Text

### ISSUE THREAD

**Issue by nhaberl** [panzerdp/voca#13]
Awesome library, would have a suggestion.
**v.stripHtml(htmlTagArray = [''])**

If any htmlTag is given within the array the strip function is limited to them otherwise the function removes all html tags.

**Comment by panzerdp** [comment]
Hello @nhaberl,

Agreed, this is an important function to have. I will probably name it `stripTags`.
It may have the following signature:

```javascript
v.stripTags(string, [allowedTags = [ ] ])
```

**Comment by IvanJov** [comment]
@panzerdp I would like to work on this issue, if you don't mind. Should probably be done in couple days 😄

**Comment by panzerdp** [comment]
@IvanJov Thanks! However I already started the function implementation.

**Comment by IvanJov** [comment]
@panzerdp Sure, no problem. If you have ideas for some other function, I would love to help, just let me know!

**Comment by panzerdp** [comment]
The function `v.stripTags()` implemented in the new version `1.1.0`.
See the docs: https://vocajs.com/#stripTags.

**Comment by IvanJov** [comment]
Great job @panzerdp !
