### ISSUE TITLE
RFC: Fuzzy compare function

### ISSUE THREAD

**Issue by dar5hak** [panzerdp/voca#14]
Hi there!

Would you be interested in a function that matches two strings while ignoring diacritics and non-alphanumeric characters? Something similar to https://github.com/dar5hak/equalsish?

### Example
```js
v.fuzzyCompare("Some String", "somestring") === true
```

If so, I would be glad to send a pull request.

**Comment by panzerdp** [comment]
Hi @dar5hak!
Thanks for the proposal. 

However I do plan to implement `v.humanize()` function that can be used to compare strings in the described way. For example:

```javascript
v.humanize("Some String"); // => "Some string"
v.humanize("SomeString");  // => "Some string"
v.humanize("Some**string!!");  // => "Some string"
```
Thank you!
