### ISSUE TITLE
behave of camelCase with a number

### ISSUE THREAD

**Issue by caoglish** [panzerdp/voca#15]
When camelCase with special characters, the characters will be removed.

But when I camelCase with a number, the number will not be removed and the letter next to the number will be capitalized. I am not sure the behave is correct or not.

version: 1.0.0

example:
```
v.camelCase("BIRD1FLIGHT")
//=> "bird1Flight"

v.camelCase("bird-1flight")
//=>"bird1Flight"

v.camelCase("bird-1flight-111-1--bi4rd 1flight")
//"bird1Flight1111Bi4Rd1Flight"
```

**Comment by panzerdp** [comment]
Yes, this is the intended behavior.
Every series of consecutive numbers is considered a separated word.

```javascript
v.camelCase('this is 2nd library version')
// => "thisIs2NdLibraryVersion"

```

**Comment by caoglish** [comment]
Thanks
