### ISSUE TITLE
Feature Request : Function for finding all possible combinations of given string.

### ISSUE THREAD

**Issue by mahesh1996** [panzerdp/voca#19]
For e.g.
If the input is **"wxyz"**  then the output of the string should be
```['w','wx','wxy','wxyz','wxz','wy','wyz','wz','x','xy','xyz','xz','y','yz','z']```

**Comment by panzerdp** [comment]
Hey @mahesh1996,
Can you let me know the use cases in web development of such a function?
Thanks.

**Comment by mahesh1996** [comment]
In web development, generally it is not needed. But it might be useful for specific purpose if backend is made in javascript (node js).

**Comment by panzerdp** [comment]
The application of such a function is for very limited situations. 
For now I am not interested to add it to the library.
Thanks for your time @mahesh1996.

**Comment by mahesh1996** [comment]
Thank you.
