### ISSUE TITLE
Implement countWords

### ISSUE THREAD

**Issue by Mevrael** [panzerdp/voca#2]
Hi, congrats with 1.0. First small feedback. When I was browsing Count section I expected to see function to count words which is often used, for example, to generate approx "time read" time.

P.S. could you provide simple plan with some cool links to get started with modern iOS dev and Swift 3 for someone with a huge dev experience in general already? How do you handle env, config, styles, layout, package management? I don't like writing a lot of small UI classes and drag'n'dropin' UI with mouse, if there are packages to use something close to CSS/HTML would be great. May be you can follow me back on https://twitter.com/mevrael so I could DM you : )

**Comment by panzerdp** [comment]
Hey @Mevrael, thanks!

I agree it's a good idea to implement the `v.countWords()`.

What about the iOS development, you could start with [Swift programming guide](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID309) and [iOS Programming: The Big Nerd Ranch Guide](https://www.amazon.com/iOS-Programming-Ranch-Guide-Guides/dp/0134390733). If you're looking for a more tranditional HTML like, check out the React native.

**Comment by panzerdp** [comment]
`v.countWords()` is implemented in version [1.0.0.alpha.2](https://github.com/panzerdp/voca/releases/tag/1.0.0-alpha.2)
