### ISSUE TITLE
from "import v from 'voca'" to "'import * as v from 'voca'"

### ISSUE THREAD

**Issue by prjherbert** [panzerdp/voca#34]
Just upgraded my Angular2+ (5) app to latest packages and my voca (which I didn't upgrade) _includes_ call stopped being recognised.  I needed to change _import v from 'voca'_ to _import * as v from 'voca'_.

Might be worth investigating/updating your docs.

Thanks for the brilliant library.

**Comment by panzerdp** [comment]
Thanks for letting me know.
