### ISSUE TITLE
Can I know how to integrate vocajs with angular?

### ISSUE THREAD

**Issue by terencetaih** [panzerdp/voca#35]
Welcome to Voca's GitHub repo!  

### Expected behavior :smile_cat:

(Please describe here the expected behavior)

### Actual behavior :crying_cat_face:

(Please describe here the actual behavior)

### Steps to reproduce :construction_worker:

(Please describe a scenario how to reproduce)

### Technical details: :wrench:

Browser/OS type:  
Node version:

**Comment by panzerdp** [comment]
This section is intended to track issues and improvements.
Your question is better suited for stackoverflow.
