### ISSUE TITLE
[Feature Request] Pascal Case

### ISSUE THREAD

**Issue by mattblackdev** [panzerdp/voca#37]
Hi,

Great lib! Is there not a pascal case function? Didn't see it in docs or issues but I'm surprised. I assume it could easily be done like this:
```
v.chain('my thing').camelCase().capitalize().value() // -> 'MyThing'
```
Would a PR be accepted for this?

**Comment by panzerdp** [comment]
Hi @mattblackdev,

Pascal case can be easily reproduced with other 2 functions, so I'm not interested in adding a new function for it.

Thanks.

**Comment by LandonSchropp** [comment]
I'd like to add a +1 to this. Yes, it can be easily replaced with `camelCase` and `capitalize`, but this is something I find myself reaching for often, and it would be more convenient to have a built-in method for it. It also feels a little incomplete with the other case variants represented.
