### ISSUE TITLE
Voca doesn't handle complex characters like కృష్ణ

### ISSUE THREAD

**Issue by kotpal** [panzerdp/voca#42]
Welcome to Voca's GitHub repo!  

### Expected behavior :smile_cat:

v.graphemes("కృష్ణ") should return (2) ["కృ", "ష్ణ"]
v.countGraphemes("కృష్ణ") should return 2

### Actual behavior :crying_cat_face:

v.graphemes("కృష్ణ") returns (5) ["క", "ృ", "ష", "్", "ణ"]
v.countGraphemes("కృష్ణ") returns 5

### Steps to reproduce :construction_worker:

v.graphemes("కృష్ణ") 
v.countGraphemes("కృష్ణ")

### Technical details: :wrench:

Browser/OS type: n/a 
Node version: n/a

**Comment by panzerdp** [comment]
@kotpal Thanks for the report.
Feel free to create a PR with the fix.

**Comment by illarionvk** [comment]
@kotpal, [grapheme-splitter library](https://github.com/orling/grapheme-splitter) splits your example into three graphemes:

```
[ 'కృ', 'ష్', 'ణ' ]
```

Would you consider it correct?

**Comment by kotpal** [comment]
No. v.graphemes("కృష్ణ") should return (2) ["కృ", "ష్ణ"]

I started using nota/split-graphemes. This issue is fixed in that library - https://github.com/nota/split-graphemes/pull/5

**Comment by panzerdp** [comment]
Voca supports a limited number of graphemes to keep the library size under minimum. For a full support, use an alternative library that has full support.
