### ISSUE TITLE
No publishing updates on NPM/Yarn?

### ISSUE THREAD

**Issue by DougCal** [panzerdp/voca#48]
Welcome to Voca's GitHub repo!  

### Expected behavior :smile_cat:

When a codebase has a significant change in GitHub, there should be something published to NPM/Yarn so people can take advantage of those updates through their package manager.

### Actual behavior :crying_cat_face:

There hasn't been a publishing of this library to NPM/Yarn in over 2 years.

### Steps to reproduce :construction_worker:

https://www.npmjs.com/package/voca?activeTab=versions
https://yarnpkg.com/package/voca

### Technical details: :wrench:

Not relevant.  I was really looking at this as a serious solution for cutting accent characters at my work, but I'm concerned of this not being published to any package management tools in so long.  Awesome work on this library, either way.  There's some very useful methods here that I would love to use.

**Comment by panzerdp** [comment]
No worries, you can use the library since it is stable enough.  
I just need to find some time to make more regular updates.
