### ISSUE TITLE
Typo in example for lowerCase method

### ISSUE THREAD

**Issue by KyleJSummers** [panzerdp/voca#9]
Documentation example shows:
```js
v.lowerCase('BLUE');
// => 'BLUE'
```

which should be
```js
v.lowerCase('BLUE');
// => 'blue'
```

I am about to submit a pull request for this fix, albeit quite small. In the future, for small documentation changes such as these, do you prefer just an issue or do you welcome pull requests?

Thanks!

**Comment by panzerdp** [comment]
Hi @KyleJSummers,
Thanks for the pull request! 
I prefer more pull requests, even for small typos.
